spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: servicecloud-config-ltyl-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: servicecloud-config-ltyl-test
    
#请保存为UTF-8
